# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderinfo',
            name='id_number',
        ),
        migrations.AddField(
            model_name='senderinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
