# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0002_auto_20180216_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_sender',
        ),
    ]
