# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0004_inputinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputinfo',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 2, 18, 2, 10, 20, 666000, tzinfo=utc)),
        ),
    ]
