# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0006_auto_20180217_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputinfo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
