# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoapp', '0009_auto_20180218_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_sender',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='SenderInfo',
        ),
    ]
